### ISSUE TITLE
Different Results When Testing with One vs. Two GPUs

### ISSUE THREAD

**Issue by IamZLT** [z0911k/SGraFormer#1]
Hi,
I found an issue with the code. I trained the model using two GPUs, but the testing results are different when I use one GPU and when I use two GPUs.

Steps to Reproduce:

Train the model using two GPUs.
Test the model using one GPU.
Test the model using two GPUs.
Compare the results.

Expected Behavior:
The results should be the same.

Observations:
The results are different when using a single GPU versus two GPUs.

**Comment by IamZLT** [comment]
This problem is solved.


`    model = sgraformer(num_frame=opt.frames, num_joints=17, in_chans=2, embed_dim_ratio=32, depth=4,
                      num_heads=8, mlp_ratio=2., qkv_bias=True, qk_scale=None, drop_path_rate=0.1)
    # model = FuseModel()

    if torch.cuda.device_count() > 1:
        print("Let's use", torch.cuda.device_count(), "GPUs!")
        model = torch.nn.DataParallel(model, device_ids=CUDA_ID).to(device)
    else:
        model = model.to(device)

    # 定义一个函数来去除 'module.' 前缀
    def remove_module_prefix(state_dict):
        new_state_dict = {}
        for k, v in state_dict.items():
            name = k[7:] if k.startswith('module.') else k  # 去除 `module.`
            new_state_dict[name] = v
        return new_state_dict

    model_dict = model.state_dict()
    if opt.previous_dir != '':
        print('pretrained model path:', opt.previous_dir)
        model_path = opt.previous_dir

        pre_dict = torch.load(model_path)

        print("=====> pre_dict:", pre_dict.keys())
        # 去除 'module.' 前缀
        state_dict = remove_module_prefix(pre_dict)
        print("=====> state_dict:", state_dict.keys())

        # 只保留在模型字典中的键值对
        state_dict = {k: v for k, v in state_dict.items() if k in model_dict.keys()}

        # 更新模型字典
        model_dict.update(state_dict)

        # 加载更新后的模型字典
        model.load_state_dict(model_dict)


    all_param = []
    lr = opt.lr
    all_param += list(model.parameters())`

**Comment by IamZLT** [comment]
This problem is solved

`   

    if torch.cuda.device_count() > 1:
        print("Let's use", torch.cuda.device_count(), "GPUs!")
        model = torch.nn.DataParallel(model, device_ids=CUDA_ID).to(device)
    else:
        model = model.to(device)

    # 定义一个函数来去除 'module.' 前缀
    def remove_module_prefix(state_dict):
        new_state_dict = {}
        for k, v in state_dict.items():
            name = k[7:] if k.startswith('module.') else k  # 去除 `module.`
            new_state_dict[name] = v
        return new_state_dict

    model_dict = model.state_dict()
    if opt.previous_dir != '':
        print('pretrained model path:', opt.previous_dir)
        model_path = opt.previous_dir

        pre_dict = torch.load(model_path)

        print("=====> pre_dict:", pre_dict.keys())
        # 去除 'module.' 前缀
        state_dict = remove_module_prefix(pre_dict)
        print("=====> state_dict:", state_dict.keys())

        # 只保留在模型字典中的键值对
        state_dict = {k: v for k, v in state_dict.items() if k in model_dict.keys()}

        # 更新模型字典
        model_dict.update(state_dict)

        # 加载更新后的模型字典
        model.load_state_dict(model_dict)


    all_param = []
    lr = opt.lr
    all_param += list(model.parameters())
`

**Comment by Jokerealm** [comment]
您好，我也遇到了这个问题，请问为什么会出现这个问题？
